services:
  n8n:
    # image: n8nio/n8n:latest -- dimitris: deleted for python fix
    build: .
    container_name: n8n-local
    restart: always
    ports:
      - "9090:5678"
    environment:
      - N8N_HOST=localhost
      - N8N_PORT=5678
      - N8N_PROTOCOL=http
      - NODE_ENV=production
      - WEBHOOK_URL=http://localhost:5678/
      - GENERIC_TIMEZONE=Europe/Amsterdam # Change to your timezone
    volumes:
      - n8n_data:/home/node/.n8n
      - /Users/zoeoggel/n8n_data:/data/host
    extra_hosts:
      - "host.docker.internal:host-gateway" # Allows n8n to talk to Ollama on your host machine
  qdrant:
    image: qdrant/qdrant:latest
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - ./qdrant_storage:/qdrant/storage


volumes:
  n8n_data: